var EventType = {
    URL_CHANGE: "URL_CHANGE",
    SUBMIT_RESULT: "SUBMIT_RESULT",
    TOGGLE_SELECTION: "TOGGLE_SELECTION",
    SUBMIT_EXTRACT_REQUEST:"SUBMIT_EXTRACT_REQUEST",
    GET_EXTRACT_REQUEST:"GET_EXTRACT_REQUEST"
};
export default EventType;
